### ISSUE TITLE
MissingSchema with valid url

### ISSUE THREAD

**Issue by clubalub** [elmoiv/redvid#22]
Keep getting the error "No schema supplied" error when using valid url's (https://v.redd.it/identifier) yet it allways errors out. 

Code i used was the video without audio example

Error log: 

/usr/bin/python3.8 /home/archie/Downloads/python/downloader.py
>> Connecting...
Traceback (most recent call last):
  File "/home/archie/Downloads/python/downloader.py", line 17, in <module>
    reddit.download()
  File "/usr/local/lib/python3.8/dist-packages/redvid/redvid.py", line 230, in download
    self.check()
  File "/usr/local/lib/python3.8/dist-packages/redvid/redvid.py", line 160, in check
    self.setup()
  File "/usr/local/lib/python3.8/dist-packages/redvid/redvid.py", line 69, in setup
    self.url = self.get(
  File "/usr/local/lib/python3.8/dist-packages/redvid/requestmaker.py", line 208, in get
    return requests.get(url, headers={'User-Agent': random.choice(self.USER_AGENTS)}, proxies=_proxies)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'v.redd.it/c8oic7ppc2751': No schema supplied. Perhaps you meant http://v.redd.it/c8oic7ppc2751?

Process finished with exit code 1
Might be an issue with my setup, not completely sure, thanks for any help given :)

**Comment by elmoiv** [comment]
I tried http://v.redd.it/c8oic7ppc2751 right now and it's working fine on my side.

You may check your setup for any incorrect configurations.
